[tool.poetry]
name = "archupdatechecker"
version = "1.0.0-dev"
description = ""
authors = ["Lucy Hancock <lucy@leh.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
auc = "auc.auc:run"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
